import postgres from 'postgres';

const sql = postgres('postgresql://postgres:ManojAlbin@2026@db.scxpmiyukhqigmuxrwch.supabase.co:5432/postgres', { ssl: 'require' });

async function main() {
  try {
    console.log('Connecting to database...');
    await sql`
      -- 1. Create Leads Table
      CREATE TABLE IF NOT EXISTS leads (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        company TEXT,
        customer_type TEXT,
        phone TEXT,
        email TEXT,
        city TEXT,
        interested_services JSONB,
        status TEXT DEFAULT 'New',
        converted_customer_id BIGINT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        created_by UUID REFERENCES auth.users(id),
        assigned_to UUID REFERENCES auth.users(id)
      );
    `;
    console.log('Leads table created.');

    await sql`
      -- 2. Create Sales Activities Table
      CREATE TABLE IF NOT EXISTS sales_activities (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
        outreach_type TEXT NOT NULL,
        date DATE NOT NULL,
        time TEXT NOT NULL,
        location TEXT,
        notes TEXT,
        outcome TEXT,
        attachments JSONB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        created_by UUID REFERENCES auth.users(id)
      );
    `;
    console.log('Sales Activities table created.');

    await sql`
      -- 3. Create Sales Follow-ups Table
      CREATE TABLE IF NOT EXISTS sales_followups (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
        activity_id BIGINT REFERENCES sales_activities(id) ON DELETE CASCADE,
        date DATE NOT NULL,
        time TEXT NOT NULL,
        method TEXT NOT NULL,
        priority TEXT DEFAULT 'Medium',
        reminder BOOLEAN DEFAULT false,
        status TEXT DEFAULT 'Pending',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        created_by UUID REFERENCES auth.users(id)
      );
    `;
    console.log('Sales Follow-ups table created.');

  } catch (error) {
    console.error('Error executing SQL:', error);
  } finally {
    await sql.end();
  }
}

main();
